### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mikeyhodl** [calpt/CoronaPandemicBot#2]
>>
Traceback (most recent call last):
  File "bot.py", line 472, in <module>
    main(config)
  File "bot.py", line 460, in main
    job_queue.run_daily(run_notify, datetime.strptime(config['notify_time'], '%H:%M').time())
KeyError: 'notify_time'

**Comment by calpt** [comment]
Thanks for mentioning this issue. `notify_time` is an additional config key that sets up daily notifications at a specified time, e.g.:
```
{
    "token": "YOUR_TOKEN_HERE",
    "notify_time": "20:00"
}
```
I just pushed a fix for the case when this key is not present.
